openapi: 3.0.0
x-stoplight:
  id: 0f56e32f16f60
info:
  title: API riferimento ANIS
  x-summary: Questo servizio ritorna l'elenco degli iscritti a uno specifico corso di un IFS.
  version: 1.0.0
  description: |
    ### Documentazione

    ## API riferimento ANIS
    La seguente documentazione API fornisce un riferimento per l'integrazione e 
    l'accesso ai dati ANIS (ANagrafe degli Studenti) relativi alle università. 
    Queste API consentono l'erogazione di servizi (e-service) che operano sui dati ANIS.

    # API Health Check
    Questa API fornisce un modo semplice per verificare lo stato di salute del sistema. 
    È un endpoint di base che può essere utilizzato per controllare se il servizio è in esecuzione correttamente.

    **Endpoint:**   GET  /status


    # Studenti iscritti a uno specifico corso di studi
    Questa API consente di ottenere il numero di studenti iscritti a un Corso di Studi specifico di un IFS. 
    Restituisce i dati relativi al corso e il conteggio degli studenti iscritti.

    **Endpoint:**   GET  /corsi/{courseName}/iscritti

    **Params:**    `{courseName}`: Nome del corso di studi.

    **Esempio di risposta:**

    ```json
    {
      "instituteName": "Università degli Studi di Milano",
      "courseType": "Corso di laurea magistrale",
      "courseName": "Ingegneria",
      "classCode": "LM-23",
      "className": "Civile e Ambientale",
      "numberRegistered": 1200
    }
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /status:
    get:
      summary: Health Check
      operationId: check-status
      description: Verificare lo stato di salute del sistema
      tags:
        - HEALTH-CHECK
      responses:
        '204':
          description: il servizio è in esecuzione correttamente.
        '500':
          description: il servizio non è in esecuzione.
  '/corsi/{courseName}/statistiche-iscritti':
    parameters:
      - schema:
          type: string
        name: courseName
        in: path
        required: true
        description: Nome del corso di studi
    get:
      summary: Studenti iscritti al Corso di Studi
      tags:
        - STUDENTI-CORSO
      responses:
        '200':
          description: Richiesta eseguita con successo
          headers:
            Content-Length:
              schema:
                type: integer
                format: int64
              description: 'utilizzato per indicare la dimensione del corpo della risposta, consentendo al client di gestire correttamente la ricezione dei dati.'
            Cache-Control:
              schema:
                type: string
              description: 'utilizzato per indicare al client o ai server intermedi come gestire la memorizzazione nella cache della risposta, ad esempio "no-cache" per impedire la memorizzazione nella cache.'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: utilizzato per consentire a determinati origini di accedere alle risorse tramite richieste cross-origin.
            X-RateLimit-Limit:
              schema:
                type: integer
                format: int64
              description: specifica il numero massimo di richieste consentite entro un determinato periodo di tempo (solitamente misurato in secondi).
            X-RateLimit-Remaining:
              schema:
                type: integer
                format: int64
              description: utilizzato per indicare il numero di richieste API rimanenti all'interno del periodo di tempo specificato dal server.
            X-RateLimit-Reset:
              schema:
                type: string
                format: date-time
              description: utilizzato per indicare il momento in cui il limite delle richieste API verrà ripristinato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentiCorso'
              examples:
                Example 1:
                  value:
                    instituteName: Università degli Studi di Milano
                    courseType: Corso di laurea magistrale
                    courseName: Ingegneria
                    classCode: LM-23
                    className: Civile e Ambientale
                    numberRegistered: 1200
        '404':
          description: Corso di studi non trovato
          headers:
            Content-Length:
              schema:
                type: integer
                format: int64
              description: 'utilizzato per indicare la dimensione del corpo della risposta, consentendo al client di gestire correttamente la ricezione dei dati.'
            Cache-Control:
              schema:
                type: string
              description: 'utilizzato per indicare al client o ai server intermedi come gestire la memorizzazione nella cache della risposta, ad esempio "no-cache" per impedire la memorizzazione nella cache.'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: utilizzato per consentire a determinati origini di accedere alle risorse tramite richieste cross-origin.
            X-RateLimit-Limit:
              schema:
                type: integer
                format: int64
              description: specifica il numero massimo di richieste consentite entro un determinato periodo di tempo (solitamente misurato in secondi).
            X-RateLimit-Remaining:
              schema:
                type: integer
                format: int64
              description: utilizzato per indicare il numero di richieste API rimanenti all'interno del periodo di tempo specificato dal server.
            X-RateLimit-Reset:
              schema:
                type: string
                format: date-time
              description: utilizzato per indicare il momento in cui il limite delle richieste API verrà ripristinato.
        '500':
          description: Errore interno del server
          headers:
            Content-Length:
              schema:
                type: integer
                format: int64
              description: 'utilizzato per indicare la dimensione del corpo della risposta, consentendo al client di gestire correttamente la ricezione dei dati.'
            Cache-Control:
              schema:
                type: string
              description: 'utilizzato per indicare al client o ai server intermedi come gestire la memorizzazione nella cache della risposta, ad esempio "no-cache" per impedire la memorizzazione nella cache.'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: utilizzato per consentire a determinati origini di accedere alle risorse tramite richieste cross-origin.
            X-RateLimit-Limit:
              schema:
                type: integer
                format: int64
              description: specifica il numero massimo di richieste consentite entro un determinato periodo di tempo (solitamente misurato in secondi).
            X-RateLimit-Remaining:
              schema:
                type: integer
                format: int64
              description: utilizzato per indicare il numero di richieste API rimanenti all'interno del periodo di tempo specificato dal server.
            X-RateLimit-Reset:
              schema:
                type: string
                format: date-time
              description: utilizzato per indicare il momento in cui il limite delle richieste API verrà ripristinato.
      operationId: studenti-iscritti-corso
      description: Restituisce il numero di studenti iscritti a un Corso di Studi specifico.
      parameters:
        - schema:
            type: string
          in: header
          name: Method
          description: Specifica il metodo HTTP utilizzato per la richiesta.
        - schema:
            type: string
          in: header
          name: Path
          description: Specifica il percorso o l'endpoint dell'API a cui viene indirizzata la richiesta.
        - schema:
            type: string
          in: header
          name: Scheme
          description: 'Specifica lo schema o il protocollo utilizzato per la comunicazione tra il client e il server, come HTTP o HTTPS.'
        - schema:
            type: string
          in: header
          name: Accept-Encoding
          description: 'Utilizzato per indicare al server le opzioni di compressione supportate dal client, come gzip o deflate.'
        - schema:
            type: string
          in: header
          name: Accept-Language
          description: 'Utilizzato per indicare al server la lingua preferita per la risposta, in modo che possa restituire la risposta nella lingua corretta, se disponibile.'
        - schema:
            type: string
          in: header
          name: Origin
          description: 'Utilizzato in contesti di sicurezza per indicare l''origine della richiesta, ad esempio durante le richieste CORS (Cross-Origin Resource Sharing).'
        - schema:
            type: string
          in: header
          name: User-Agent
          description: 'Utilizzato per identificare il client che sta effettuando la richiesta, ad esempio il browser e la versione utilizzata.'
components:
  schemas:
    StudentiCorso:
      type: object
      x-examples:
        Example 1:
          instituteName: Università degli Studi di Milano
          courseType: Corso di laurea magistrale
          courseName: Ingegneria
          classCode: LM-23
          className: Civile e Ambientale
          numberRegistered: 1200
      description: Numero studenti iscritti a un corso
      properties:
        instituteName:
          type: string
          description: Nome dell'istituto
          readOnly: true
        courseType:
          type: string
          description: Tipo di corso di studio
          example: 'laurea, laurea magistrale, dottorato di ricerca, specializzazione, master, formazione professionale'
          readOnly: true
        courseName:
          type: string
          description: Denominazione del corso di studio
          example: 'ingegneria, economia, giurisprudenza, medicina, scienze umanistiche, scienze sociali, informatica, arte e design'
          readOnly: true
        classCode:
          type: string
          description: Codice della classe di studio
          pattern: '^[A-Za-z0-9-]+$'
          example: L-8
          readOnly: true
        className:
          type: string
          description: Denominazione della classe di studio
          example: 'Informatica, Meccanica, Elettronica, Civile'
          readOnly: true
        numberRegistered:
          type: integer
          description: Numero di iscritti al corso
          format: int32
          readOnly: true
  requestBodies: {}
  responses: {}
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: API-ANIS
  - name: HEALTH-CHECK
  - name: STUDENTI-CORSO
